server:
  port: 8080

spring:
  application:
    name: hotel-reservation-backend
  data:
    mongodb:
      uri: mongodb+srv://jlopezbenavides73_db_user:2945SebAs@cluster0.yapzpyl.mongodb.net/?appName=Cluster0
      database: hotel-db

logging:
  level:
    root: INFO
    com.hotel.reservation: DEBUG
